### ISSUE TITLE
Package support

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/atom-stata-exec#2]
@kylebarron : In short... not really. :) Still works for me, and since there have been no issues (since I apparently never turned them on... oops!) had kinda forgotten about it. 

In general it seems like Atom separately syntax-highlighting packages from execution packages, so I don't know that it's necessary optimal to roll everything together, but you are welcome to push anything you want to this, or if you create a better alternative, happy to delete/merge this like we did with syntax.

**Comment by nickeubank** [comment]
Invited you as collaborator so you can do as you see fit here!

**Comment by kylebarron** [comment]
I have code working to do line-by-line execution through Applescript. I haven't added full do-file support yet but that should be really easy and quick to do.

I think I'm more likely to try to create a repo on my Github account. Once I add the do-file support it should be a superset of your code.

Also, I discovered Stata's automation API yesterday and have some ideas I want to try out: for example, it should be entirely possible to create an Autocomplete provider that uses the current variable names and macro names in Stata.

**Comment by nickeubank** [comment]
GREAT! Way to contribute to the public goods!

**Comment by kylebarron** [comment]
I'm not sure how easy it would be to create something like that, but I'd be interested in trying.

**Comment by kylebarron** [comment]
I got all of the package ported to Stata. Test it out! It works for me on my computer. Important bits from the README:

## Usage
- `cmd-enter`: send selection or current line to Stata.
- `shift-cmd-d`: send entire file to Stata. (File must be saved first. This runs `do "/path/to/current/file"`)
- `shift-alt-p`: send the previous command.
- `shift-cmd-c`: change Stata's working directory to that of current file.
- `shift-cmd-p`: send paragraph under current cursor. A paragraph is a region enclosed by whitespace.
- `shift-cmd-r`: send program definition under current cursor. For example, all the lines in the below snippet would be sent to Stata:
    ```stata
    program define myProgram
        // program contents
    end
    ```

## Configuration

- Which App
  - Select StataIC, StataSE, or StataMP, depending on which version of Stata you have.
- Advance Position
  - If checked, move cursor to the next line/paragraph after running the current line/paragraph.
- Focus Window
  - If checked, bring the Stata window to focus when sending code.
  - Otherwise, code runs in the background and the screen remains focused on Atom.
- Notifications
  - If checked, a pop-up notification will appear when a paragraph or function is not identified.
- Skip Comments
  - If this and Advance Position are checked, the after running a line, the cursor will move to the next uncommented line.

**Comment by nickeubank** [comment]
wow, amazing. I'm on a deadline right at the moment, but will demo it soon! Thanks so much for the great work! (also, you clearly have a better grip on Atom packages than me at this point, so if you're in a hurry and would like to just release, please feel free. :) )

**Comment by kylebarron** [comment]
I'm happy to release it, but unless you want to keep your package listed on Atom's package manager, I'd be happy to release this named as `stata-exec` so that people who have previously downloaded your package are upgraded automatically. If you want that, I think you'd have to do `apm unpublish stata-exec` before I can publish this as the same name.

**Comment by nickeubank** [comment]
done! let me know if you have issues. 

![screen shot 2017-11-13 at 12 56 42 pm](https://user-images.githubusercontent.com/9683693/32743470-1d45acf4-c872-11e7-874e-0ed5e5c69951.png)

**Comment by kylebarron** [comment]
https://atom.io/packages/stata-exec
It's online! thanks!
